# Generated by Django 4.0.4 on 2022-05-24 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_client_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cумма перевода')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
                ('fk_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='core.bankaccount', verbose_name='От')),
                ('fk_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='core.bankaccount', verbose_name='Кому')),
            ],
        ),
    ]
